import { useEffect, useState } from "react";
import { api } from "../api";
import RecipeForm, { emptyRecipe } from "../components/RecipeForm";
import RecipeView, { recipeInput } from "../components/RecipeView";

export default function SavedRecipes() {
  const [recipes, setRecipes] = useState([]);
  const [selected, setSelected] = useState(null);
  const [editing, setEditing] = useState(null);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);

  async function refresh(preferredId) {
    const rows = await api("/api/recipes");
    setRecipes(rows);
    const next = preferredId
      ? rows.find((row) => row.id === preferredId)
      : rows.find((row) => row.id === selected?.id) || rows[0] || null;
    setSelected(next || null);
  }

  useEffect(() => {
    refresh().catch((err) => setError(err.message));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function save(body) {
    setSaving(true);
    setError("");
    try {
      const data = editing?.id && editing.id !== "new"
        ? await api(`/api/recipes/${editing.id}`, { method: "PUT", body })
        : await api("/api/recipes", { method: "POST", body: { ...body, source: "manual" } });
      setEditing(null);
      await refresh(data.id);
    } catch (err) {
      setError(err.message);
    } finally {
      setSaving(false);
    }
  }

  async function remove(recipe) {
    setError("");
    try {
      await api(`/api/recipes/${recipe.id}`, { method: "DELETE" });
      setSelected(null);
      await refresh();
    } catch (err) {
      setError(err.message);
    }
  }

  return (
    <section>
      <div className="recipe-title">
        <div>
          <h2>Saved recipes</h2>
          <p className="muted">
            Add your own cooking method or reopen recipes generated by HealthPro.
            Nutrition is recalculated whenever you save.
          </p>
        </div>
        <button
          onClick={() => setEditing({ ...emptyRecipe(), id: "new" })}
        >
          + Add my recipe
        </button>
      </div>
      {error && <p className="error">{error}</p>}

      {editing ? (
        <>
          <button className="ghost" onClick={() => setEditing(null)}>← Cancel</button>
          <RecipeForm
            key={editing.id}
            initial={editing}
            onSubmit={save}
            submitLabel={saving ? "Calculating…" : "Calculate nutrition and save"}
          />
        </>
      ) : (
        <div className="recipe-library">
          <aside className="card">
            <h3>Your recipes</h3>
            {!recipes.length && <p className="muted">No saved recipes yet.</p>}
            <ul className="list">
              {recipes.map((recipe) => (
                <li key={recipe.id}>
                  <button
                    className={selected?.id === recipe.id ? "pick on" : "pick"}
                    onClick={() => setSelected(recipe)}
                  >
                    <strong>{recipe.name}</strong>
                    <span>{recipe.servings} serving(s) · {recipe.source}</span>
                  </button>
                </li>
              ))}
            </ul>
          </aside>
          <div>
            {selected && (
              <RecipeView
                recipe={selected}
                actions={
                  <>
                    <button
                      className="ghost"
                      onClick={() => setEditing({ ...recipeInput(selected), id: selected.id })}
                    >
                      Edit
                    </button>
                    <button className="danger" onClick={() => remove(selected)}>Delete</button>
                  </>
                }
              />
            )}
          </div>
        </div>
      )}
    </section>
  );
}
