"""Starter catalog: common Indian foods with public-domain-style per-100g values.

Values are representative (USDA-equivalent ingredients + typical cooked yields),
not a copy of the official IFCT 2017 tables. Drop an IFCT export at
backend/data/ifct_import.json to override/extend (see Instructions.md).
"""

from .models import FoodItem, Nutrients

# id, name, aliases, form, default_g, piece_g, notes, nutrients per 100g
_RAW = [
    (
        "rice_cooked",
        "Rice, cooked (plain)",
        ["chawal", "bhat", "steamed rice", "white rice cooked"],
        "cooked",
        150,
        None,
        "Mostly starch; low micronutrient density unless fortified.",
        dict(energy_kcal=130, protein_g=2.7, carb_g=28, fat_g=0.3, fiber_g=0.4, sodium_mg=1, potassium_mg=35, calcium_mg=10, iron_mg=0.2, magnesium_mg=12, zinc_mg=0.5, vitamin_a_ug=0, vitamin_c_mg=0, folate_ug=3, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "roti_wheat",
        "Roti / chapati (whole wheat)",
        ["chapati", "phulka", "roti", "atta roti"],
        "cooked",
        40,
        40,
        "Whole wheat contributes fiber, iron, and B vitamins versus refined flour.",
        dict(energy_kcal=297, protein_g=9.6, carb_g=51, fat_g=7.5, fiber_g=7, sodium_mg=298, potassium_mg=166, calcium_mg=40, iron_mg=2.7, magnesium_mg=44, zinc_mg=1.2, vitamin_a_ug=0, vitamin_c_mg=0, folate_ug=28, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "idli",
        "Idli",
        ["idly", "rice idli"],
        "cooked",
        30,
        30,
        "Fermented rice-dal steam cake; modest protein, low fat.",
        dict(energy_kcal=135, protein_g=3.8, carb_g=26, fat_g=0.7, fiber_g=1.5, sodium_mg=210, potassium_mg=70, calcium_mg=18, iron_mg=0.8, magnesium_mg=14, zinc_mg=0.4, vitamin_a_ug=0, vitamin_c_mg=0, folate_ug=18, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "dosa",
        "Dosa (plain)",
        ["dose", "plain dosa"],
        "cooked",
        80,
        80,
        "Fermented batter; oil on the tawa raises fat and energy.",
        dict(energy_kcal=184, protein_g=4.1, carb_g=29, fat_g=5.5, fiber_g=1.2, sodium_mg=240, potassium_mg=80, calcium_mg=20, iron_mg=0.9, magnesium_mg=16, zinc_mg=0.4, vitamin_a_ug=0, vitamin_c_mg=0, folate_ug=20, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "poha",
        "Poha (cooked, with oil and peanuts)",
        ["aval", "flattened rice", "kanda poha"],
        "cooked",
        150,
        None,
        "Iron from poha and peanuts; oil and peanuts drive calories.",
        dict(energy_kcal=180, protein_g=4.2, carb_g=28, fat_g=5.8, fiber_g=2.1, sodium_mg=280, potassium_mg=140, calcium_mg=22, iron_mg=3.5, magnesium_mg=28, zinc_mg=0.7, vitamin_a_ug=15, vitamin_c_mg=4, folate_ug=12, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "upma",
        "Upma (rava)",
        ["uppumavu", "sooji upma"],
        "cooked",
        150,
        None,
        "Semolina plus vegetables and oil; sodium depends on salt.",
        dict(energy_kcal=145, protein_g=3.5, carb_g=22, fat_g=4.8, fiber_g=1.8, sodium_mg=310, potassium_mg=95, calcium_mg=18, iron_mg=1.1, magnesium_mg=18, zinc_mg=0.5, vitamin_a_ug=40, vitamin_c_mg=6, folate_ug=10, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "toor_dal_cooked",
        "Toor / arhar dal (cooked)",
        ["tuvar dal", "pigeon pea", "dal tadka toor"],
        "cooked",
        150,
        None,
        "Good plant protein and folate; tadka oil is extra energy not always in this row.",
        dict(energy_kcal=116, protein_g=7.2, carb_g=19.5, fat_g=0.4, fiber_g=6.5, sodium_mg=5, potassium_mg=228, calcium_mg=27, iron_mg=1.3, magnesium_mg=36, zinc_mg=0.9, vitamin_a_ug=1, vitamin_c_mg=0.7, folate_ug=107, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "moong_dal_cooked",
        "Moong dal (cooked)",
        ["mung dal", "green gram dal"],
        "cooked",
        150,
        None,
        "Light dal; useful protein with relatively easy digestion.",
        dict(energy_kcal=105, protein_g=7, carb_g=19, fat_g=0.4, fiber_g=6, sodium_mg=4, potassium_mg=266, calcium_mg=27, iron_mg=1.4, magnesium_mg=48, zinc_mg=0.8, vitamin_a_ug=2, vitamin_c_mg=1, folate_ug=159, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "masoor_dal_cooked",
        "Masoor dal (cooked)",
        ["red lentil", "masoor"],
        "cooked",
        150,
        None,
        "Lentils supply iron and folate; pair with vitamin C foods for iron absorption.",
        dict(energy_kcal=116, protein_g=9, carb_g=20, fat_g=0.4, fiber_g=7.9, sodium_mg=2, potassium_mg=369, calcium_mg=19, iron_mg=3.3, magnesium_mg=36, zinc_mg=1.3, vitamin_a_ug=0, vitamin_c_mg=1.5, folate_ug=181, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "chana_cooked",
        "Chickpeas / chana (cooked)",
        ["chole", "kabuli chana", "bengal gram"],
        "cooked",
        150,
        None,
        "Fiber and plant protein; chole masala oil/salt not fully included.",
        dict(energy_kcal=164, protein_g=8.9, carb_g=27, fat_g=2.6, fiber_g=7.6, sodium_mg=7, potassium_mg=291, calcium_mg=49, iron_mg=2.9, magnesium_mg=48, zinc_mg=1.5, vitamin_a_ug=1, vitamin_c_mg=1.3, folate_ug=172, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "rajma_cooked",
        "Rajma (cooked kidney beans)",
        ["kidney beans", "rajmah"],
        "cooked",
        150,
        None,
        "High fiber and iron; gravy oil is extra.",
        dict(energy_kcal=127, protein_g=8.7, carb_g=22.8, fat_g=0.5, fiber_g=6.4, sodium_mg=2, potassium_mg=403, calcium_mg=28, iron_mg=2.2, magnesium_mg=45, zinc_mg=1, vitamin_a_ug=0, vitamin_c_mg=1.2, folate_ug=130, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "sambar",
        "Sambar",
        ["sambhar"],
        "cooked",
        200,
        None,
        "Dal plus vegetables; sodium from salt and sambar powder.",
        dict(energy_kcal=65, protein_g=3.2, carb_g=9.5, fat_g=1.6, fiber_g=2.8, sodium_mg=280, potassium_mg=180, calcium_mg=32, iron_mg=1.1, magnesium_mg=22, zinc_mg=0.4, vitamin_a_ug=45, vitamin_c_mg=8, folate_ug=32, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "curd",
        "Dahi / curd (plain)",
        ["yogurt", "thayir", "dahi"],
        "cooked",
        100,
        None,
        "Calcium, protein, and some B12; unsweetened is preferable.",
        dict(energy_kcal=61, protein_g=3.5, carb_g=4.7, fat_g=3.3, fiber_g=0, sodium_mg=46, potassium_mg=155, calcium_mg=121, iron_mg=0.1, magnesium_mg=12, zinc_mg=0.6, vitamin_a_ug=27, vitamin_c_mg=0.5, folate_ug=7, vitamin_b12_ug=0.4, vitamin_d_ug=0.1),
    ),
    (
        "milk_buffalo",
        "Milk, buffalo",
        ["buffalow milk", "bhains ka doodh"],
        "raw",
        200,
        None,
        "Higher fat and energy than cow milk; good calcium.",
        dict(energy_kcal=97, protein_g=3.8, carb_g=5.2, fat_g=6.9, fiber_g=0, sodium_mg=52, potassium_mg=178, calcium_mg=169, iron_mg=0.1, magnesium_mg=31, zinc_mg=0.5, vitamin_a_ug=53, vitamin_c_mg=2.3, folate_ug=6, vitamin_b12_ug=0.4, vitamin_d_ug=0.1),
    ),
    (
        "milk_cow",
        "Milk, cow (whole)",
        ["doodh", "cow milk"],
        "raw",
        200,
        None,
        "Calcium, B12, and riboflavin; whole milk is energy-dense.",
        dict(energy_kcal=61, protein_g=3.2, carb_g=4.8, fat_g=3.3, fiber_g=0, sodium_mg=43, potassium_mg=150, calcium_mg=113, iron_mg=0, magnesium_mg=10, zinc_mg=0.4, vitamin_a_ug=46, vitamin_c_mg=0, folate_ug=5, vitamin_b12_ug=0.45, vitamin_d_ug=0.1),
    ),
    (
        "paneer",
        "Paneer",
        ["indian cottage cheese"],
        "cooked",
        50,
        None,
        "Concentrated milk protein and fat; sodium varies with preparation.",
        dict(energy_kcal=265, protein_g=18.3, carb_g=1.2, fat_g=20.8, fiber_g=0, sodium_mg=18, potassium_mg=104, calcium_mg=208, iron_mg=0.2, magnesium_mg=13, zinc_mg=1.9, vitamin_a_ug=97, vitamin_c_mg=0, folate_ug=7, vitamin_b12_ug=0.8, vitamin_d_ug=0.1),
    ),
    (
        "egg_boiled",
        "Egg, boiled",
        ["anda", "whole egg"],
        "cooked",
        50,
        50,
        "Complete protein, choline, B12; yolk holds most fat and vitamin A.",
        dict(energy_kcal=155, protein_g=12.6, carb_g=1.1, fat_g=10.6, fiber_g=0, sodium_mg=124, potassium_mg=126, calcium_mg=50, iron_mg=1.2, magnesium_mg=10, zinc_mg=1.1, vitamin_a_ug=160, vitamin_c_mg=0, folate_ug=44, vitamin_b12_ug=1.1, vitamin_d_ug=2.2),
    ),
    (
        "chicken_curry",
        "Chicken curry (home style)",
        ["murgh", "chicken gravy"],
        "cooked",
        150,
        None,
        "Protein-rich; oil and coconut/cream change calories a lot.",
        dict(energy_kcal=165, protein_g=14, carb_g=4, fat_g=10, fiber_g=0.8, sodium_mg=390, potassium_mg=220, calcium_mg=22, iron_mg=0.9, magnesium_mg=18, zinc_mg=1.1, vitamin_a_ug=35, vitamin_c_mg=3, folate_ug=8, vitamin_b12_ug=0.3, vitamin_d_ug=0.2),
    ),
    (
        "fish_fry",
        "Fish fry (typical)",
        ["meen fry", "machli"],
        "cooked",
        100,
        None,
        "Protein and often B12; frying oil raises fat. Species vary widely.",
        dict(energy_kcal=220, protein_g=19, carb_g=6, fat_g=13, fiber_g=0.2, sodium_mg=420, potassium_mg=280, calcium_mg=30, iron_mg=0.8, magnesium_mg=28, zinc_mg=0.6, vitamin_a_ug=20, vitamin_c_mg=1, folate_ug=10, vitamin_b12_ug=1.8, vitamin_d_ug=4),
    ),
    (
        "palak_cooked",
        "Palak / spinach (cooked)",
        ["spinach", "keerai"],
        "cooked",
        80,
        None,
        "Folate, vitamin A, vitamin K, and some iron; oxalates limit iron uptake.",
        dict(energy_kcal=23, protein_g=3, carb_g=3.8, fat_g=0.3, fiber_g=2.4, sodium_mg=70, potassium_mg=466, calcium_mg=136, iron_mg=3.6, magnesium_mg=87, zinc_mg=0.8, vitamin_a_ug=469, vitamin_c_mg=10, folate_ug=146, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "aloo_sabzi",
        "Aloo sabzi (dry, with oil)",
        ["potato curry", "aloo fry"],
        "cooked",
        120,
        None,
        "Potassium from potato; oil and salt drive energy and sodium.",
        dict(energy_kcal=140, protein_g=2, carb_g=18, fat_g=7, fiber_g=1.8, sodium_mg=250, potassium_mg=360, calcium_mg=12, iron_mg=0.6, magnesium_mg=20, zinc_mg=0.3, vitamin_a_ug=8, vitamin_c_mg=9, folate_ug=12, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "bhindi",
        "Bhindi / okra (cooked)",
        ["lady finger", "vendakkai"],
        "cooked",
        100,
        None,
        "Fiber and modest micronutrients; oil in stir-fry adds calories.",
        dict(energy_kcal=90, protein_g=1.9, carb_g=7.5, fat_g=6, fiber_g=3.2, sodium_mg=180, potassium_mg=250, calcium_mg=77, iron_mg=0.6, magnesium_mg=36, zinc_mg=0.5, vitamin_a_ug=18, vitamin_c_mg=13, folate_ug=46, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "tomato",
        "Tomato (raw)",
        ["tamatar"],
        "raw",
        80,
        None,
        "Vitamin C and lycopene; very low energy.",
        dict(energy_kcal=18, protein_g=0.9, carb_g=3.9, fat_g=0.2, fiber_g=1.2, sodium_mg=5, potassium_mg=237, calcium_mg=10, iron_mg=0.3, magnesium_mg=11, zinc_mg=0.2, vitamin_a_ug=42, vitamin_c_mg=14, folate_ug=15, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "onion",
        "Onion (raw)",
        ["pyaz", "vengayam"],
        "raw",
        50,
        None,
        "Flavor vegetable; small vitamin C contribution.",
        dict(energy_kcal=40, protein_g=1.1, carb_g=9.3, fat_g=0.1, fiber_g=1.7, sodium_mg=4, potassium_mg=146, calcium_mg=23, iron_mg=0.2, magnesium_mg=10, zinc_mg=0.2, vitamin_a_ug=0, vitamin_c_mg=7.4, folate_ug=19, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "banana",
        "Banana",
        ["kela"],
        "raw",
        118,
        118,
        "Potassium and quick carbs; useful around exercise.",
        dict(energy_kcal=89, protein_g=1.1, carb_g=23, fat_g=0.3, fiber_g=2.6, sodium_mg=1, potassium_mg=358, calcium_mg=5, iron_mg=0.3, magnesium_mg=27, zinc_mg=0.2, vitamin_a_ug=3, vitamin_c_mg=8.7, folate_ug=20, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "apple",
        "Apple",
        ["seb"],
        "raw",
        150,
        150,
        "Fiber and water; limited micronutrient density.",
        dict(energy_kcal=52, protein_g=0.3, carb_g=14, fat_g=0.2, fiber_g=2.4, sodium_mg=1, potassium_mg=107, calcium_mg=6, iron_mg=0.1, magnesium_mg=5, zinc_mg=0, vitamin_a_ug=3, vitamin_c_mg=4.6, folate_ug=3, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "mango",
        "Mango",
        ["aam"],
        "raw",
        150,
        None,
        "Vitamin A (beta-carotene) and vitamin C; natural sugars.",
        dict(energy_kcal=60, protein_g=0.8, carb_g=15, fat_g=0.4, fiber_g=1.6, sodium_mg=1, potassium_mg=168, calcium_mg=11, iron_mg=0.2, magnesium_mg=10, zinc_mg=0.1, vitamin_a_ug=54, vitamin_c_mg=36, folate_ug=43, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "ragi_mudde",
        "Ragi / finger millet (cooked porridge or mudde)",
        ["nachni", "finger millet"],
        "cooked",
        150,
        None,
        "Standout calcium among cereals; also iron and fiber.",
        dict(energy_kcal=120, protein_g=3.6, carb_g=25, fat_g=0.8, fiber_g=3.6, sodium_mg=4, potassium_mg=180, calcium_mg=160, iron_mg=1.9, magnesium_mg=50, zinc_mg=0.8, vitamin_a_ug=0, vitamin_c_mg=0, folate_ug=8, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "bajra_roti",
        "Bajra roti",
        ["pearl millet roti"],
        "cooked",
        50,
        50,
        "Millet roti with iron, magnesium, and fiber.",
        dict(energy_kcal=250, protein_g=7, carb_g=48, fat_g=4.2, fiber_g=8, sodium_mg=180, potassium_mg=220, calcium_mg=30, iron_mg=4.5, magnesium_mg=80, zinc_mg=1.8, vitamin_a_ug=4, vitamin_c_mg=0, folate_ug=25, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "peanuts",
        "Peanuts (roasted)",
        ["groundnut", "mungfali", "shengdana"],
        "cooked",
        20,
        None,
        "Energy-dense fats, magnesium, and plant protein.",
        dict(energy_kcal=567, protein_g=25.8, carb_g=16, fat_g=49, fiber_g=8.5, sodium_mg=18, potassium_mg=705, calcium_mg=92, iron_mg=4.6, magnesium_mg=168, zinc_mg=3.3, vitamin_a_ug=0, vitamin_c_mg=0, folate_ug=240, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "ghee",
        "Ghee",
        ["clarified butter"],
        "cooked",
        5,
        None,
        "Almost pure fat; vitamin A; easy to under-log in tadka.",
        dict(energy_kcal=900, protein_g=0, carb_g=0, fat_g=100, fiber_g=0, sodium_mg=2, potassium_mg=0, calcium_mg=4, iron_mg=0, magnesium_mg=0, zinc_mg=0, vitamin_a_ug=840, vitamin_c_mg=0, folate_ug=0, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "oil_veg",
        "Cooking oil (vegetable)",
        ["sunflower oil", "groundnut oil", "refined oil"],
        "cooked",
        5,
        None,
        "Log tadka and frying oil separately or calories will look too low.",
        dict(energy_kcal=884, protein_g=0, carb_g=0, fat_g=100, fiber_g=0, sodium_mg=0, potassium_mg=0, calcium_mg=0, iron_mg=0, magnesium_mg=0, zinc_mg=0, vitamin_a_ug=0, vitamin_c_mg=0, folate_ug=0, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "sugar",
        "Sugar",
        ["chini", "table sugar"],
        "raw",
        5,
        None,
        "Energy only; no meaningful micronutrients.",
        dict(energy_kcal=387, protein_g=0, carb_g=100, fat_g=0, fiber_g=0, sodium_mg=1, potassium_mg=2, calcium_mg=1, iron_mg=0, magnesium_mg=0, zinc_mg=0, vitamin_a_ug=0, vitamin_c_mg=0, folate_ug=0, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "tea_milk",
        "Tea with milk and sugar (one cup)",
        ["chai"],
        "cooked",
        150,
        150,
        "Most calories come from milk and sugar, not the tea leaves.",
        dict(energy_kcal=45, protein_g=1.2, carb_g=7.5, fat_g=1.2, fiber_g=0, sodium_mg=18, potassium_mg=60, calcium_mg=40, iron_mg=0, magnesium_mg=6, zinc_mg=0.1, vitamin_a_ug=12, vitamin_c_mg=0, folate_ug=2, vitamin_b12_ug=0.1, vitamin_d_ug=0),
    ),
    (
        "biryani",
        "Biryani (mixed, typical serving density)",
        ["chicken biryani", "veg biryani"],
        "cooked",
        250,
        None,
        "Rice plus fat and protein; restaurant portions vary a lot.",
        dict(energy_kcal=170, protein_g=7, carb_g=22, fat_g=6.5, fiber_g=1.2, sodium_mg=380, potassium_mg=140, calcium_mg=25, iron_mg=1.1, magnesium_mg=18, zinc_mg=0.7, vitamin_a_ug=20, vitamin_c_mg=2, folate_ug=12, vitamin_b12_ug=0.15, vitamin_d_ug=0.1),
    ),
    # Raw cooking staples. Recipes list these constantly and USDA either misses
    # them or answers with a prepared dish, so they are priced locally instead.
    (
        "green_chilli",
        "Green chilli",
        ["green chillies", "green chili", "hari mirch", "chilli", "chillies"],
        "raw",
        10,
        5,
        "Very high vitamin C for its weight, but eaten in small amounts.",
        dict(energy_kcal=40, protein_g=1.9, carb_g=9.5, fat_g=0.4, fiber_g=1.5, sodium_mg=7, potassium_mg=340, calcium_mg=18, iron_mg=1.2, magnesium_mg=25, zinc_mg=0.3, vitamin_a_ug=59, vitamin_c_mg=240, folate_ug=23, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "curry_leaves",
        "Curry leaves",
        ["kadi patta", "curry leaf", "karivepaku"],
        "raw",
        2,
        None,
        "Used as a tempering aromatic; the quantity eaten is tiny.",
        dict(energy_kcal=108, protein_g=6.1, carb_g=18.7, fat_g=1, fiber_g=6.4, sodium_mg=11, potassium_mg=510, calcium_mg=830, iron_mg=0.9, magnesium_mg=44, zinc_mg=0.2, vitamin_a_ug=380, vitamin_c_mg=4, folate_ug=93, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "coriander_leaves",
        "Coriander leaves",
        ["cilantro", "dhania patta", "fresh coriander", "coriander"],
        "raw",
        10,
        None,
        "Garnish quantities; contributes vitamin A and K more than calories.",
        dict(energy_kcal=23, protein_g=2.1, carb_g=3.7, fat_g=0.5, fiber_g=2.8, sodium_mg=46, potassium_mg=521, calcium_mg=67, iron_mg=1.8, magnesium_mg=26, zinc_mg=0.5, vitamin_a_ug=337, vitamin_c_mg=27, folate_ug=62, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "ginger",
        "Ginger, fresh",
        ["adrak", "ginger root", "fresh ginger"],
        "raw",
        10,
        None,
        "Aromatic; negligible contribution at normal recipe quantities.",
        dict(energy_kcal=80, protein_g=1.8, carb_g=17.8, fat_g=0.8, fiber_g=2, sodium_mg=13, potassium_mg=415, calcium_mg=16, iron_mg=0.6, magnesium_mg=43, zinc_mg=0.3, vitamin_a_ug=0, vitamin_c_mg=5, folate_ug=11, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "garlic",
        "Garlic",
        ["lehsun", "garlic cloves", "fresh garlic"],
        "raw",
        6,
        3,
        "Strong flavour per gram; small amounts used.",
        dict(energy_kcal=149, protein_g=6.4, carb_g=33, fat_g=0.5, fiber_g=2.1, sodium_mg=17, potassium_mg=401, calcium_mg=181, iron_mg=1.7, magnesium_mg=25, zinc_mg=1.2, vitamin_a_ug=0, vitamin_c_mg=31, folate_ug=3, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "ginger_garlic_paste",
        "Ginger-garlic paste",
        ["ginger garlic paste", "adrak lehsun paste"],
        "raw",
        15,
        None,
        "Equal parts ginger and garlic ground together.",
        dict(energy_kcal=115, protein_g=4.1, carb_g=25, fat_g=0.7, fiber_g=2.1, sodium_mg=15, potassium_mg=408, calcium_mg=99, iron_mg=1.2, magnesium_mg=34, zinc_mg=0.8, vitamin_a_ug=0, vitamin_c_mg=18, folate_ug=7, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "rice_raw",
        "Rice, raw (milled)",
        ["basmati rice", "raw rice", "uncooked rice", "sona masoori"],
        "raw",
        75,
        None,
        "Dry weight. Absorbs roughly 2.5x its weight in water when cooked.",
        dict(energy_kcal=356, protein_g=6.8, carb_g=78, fat_g=0.5, fiber_g=2.8, sodium_mg=2, potassium_mg=100, calcium_mg=10, iron_mg=0.7, magnesium_mg=20, zinc_mg=1.2, vitamin_a_ug=0, vitamin_c_mg=0, folate_ug=10, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "wheat_flour",
        "Wheat flour (atta)",
        ["atta", "whole wheat flour", "gehun ka atta"],
        "raw",
        60,
        None,
        "Dry weight, before water is added for dough.",
        dict(energy_kcal=341, protein_g=12.1, carb_g=69, fat_g=1.7, fiber_g=11.2, sodium_mg=2, potassium_mg=363, calcium_mg=34, iron_mg=3.9, magnesium_mg=138, zinc_mg=2.9, vitamin_a_ug=0, vitamin_c_mg=0, folate_ug=44, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "besan",
        "Besan (gram flour)",
        ["gram flour", "chickpea flour", "chana atta"],
        "raw",
        50,
        None,
        "Higher protein and fiber than wheat flour.",
        dict(energy_kcal=387, protein_g=22.4, carb_g=58, fat_g=6.7, fiber_g=10.8, sodium_mg=64, potassium_mg=846, calcium_mg=45, iron_mg=4.9, magnesium_mg=166, zinc_mg=2.8, vitamin_a_ug=2, vitamin_c_mg=0, folate_ug=437, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "potato",
        "Potato",
        ["aloo", "potatoes"],
        "raw",
        120,
        120,
        "Starchy; potassium and vitamin C are the main micronutrients.",
        dict(energy_kcal=77, protein_g=2, carb_g=17.5, fat_g=0.1, fiber_g=2.2, sodium_mg=6, potassium_mg=425, calcium_mg=12, iron_mg=0.8, magnesium_mg=23, zinc_mg=0.3, vitamin_a_ug=0, vitamin_c_mg=19.7, folate_ug=15, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "carrot",
        "Carrot",
        ["gajar", "carrots"],
        "raw",
        80,
        70,
        "Dense source of provitamin A carotenoids.",
        dict(energy_kcal=41, protein_g=0.9, carb_g=9.6, fat_g=0.2, fiber_g=2.8, sodium_mg=69, potassium_mg=320, calcium_mg=33, iron_mg=0.3, magnesium_mg=12, zinc_mg=0.2, vitamin_a_ug=835, vitamin_c_mg=5.9, folate_ug=19, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "capsicum",
        "Capsicum / bell pepper",
        ["bell pepper", "shimla mirch", "green capsicum"],
        "raw",
        80,
        120,
        "Very high vitamin C, especially when eaten raw.",
        dict(energy_kcal=26, protein_g=1, carb_g=6, fat_g=0.3, fiber_g=2.1, sodium_mg=4, potassium_mg=211, calcium_mg=10, iron_mg=0.3, magnesium_mg=10, zinc_mg=0.1, vitamin_a_ug=18, vitamin_c_mg=80.4, folate_ug=10, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "cucumber",
        "Cucumber",
        ["kheera", "cucumbers"],
        "raw",
        100,
        200,
        "Mostly water; useful bulk with almost no calories.",
        dict(energy_kcal=15, protein_g=0.7, carb_g=3.6, fat_g=0.1, fiber_g=0.5, sodium_mg=2, potassium_mg=147, calcium_mg=16, iron_mg=0.3, magnesium_mg=13, zinc_mg=0.2, vitamin_a_ug=5, vitamin_c_mg=2.8, folate_ug=7, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "lemon_juice",
        "Lemon juice",
        ["nimbu ras", "lime juice", "nimbu juice"],
        "liquid",
        15,
        None,
        "Vitamin C and acidity; improves iron absorption from the meal.",
        dict(energy_kcal=22, protein_g=0.35, carb_g=6.9, fat_g=0.24, fiber_g=0.3, sodium_mg=1, potassium_mg=103, calcium_mg=6, iron_mg=0.1, magnesium_mg=6, zinc_mg=0.1, vitamin_a_ug=0, vitamin_c_mg=38.7, folate_ug=20, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "butter",
        "Butter",
        ["makhan", "table butter"],
        "raw",
        10,
        None,
        "Almost entirely fat, with saturated fat dominant.",
        dict(energy_kcal=717, protein_g=0.9, carb_g=0.1, fat_g=81, fiber_g=0, sodium_mg=643, potassium_mg=24, calcium_mg=24, iron_mg=0, magnesium_mg=2, zinc_mg=0.1, vitamin_a_ug=684, vitamin_c_mg=0, folate_ug=3, vitamin_b12_ug=0.2, vitamin_d_ug=1.5),
    ),
    (
        "mayonnaise",
        "Mayonnaise",
        ["mayo", "eggless mayonnaise"],
        "raw",
        15,
        None,
        "Oil-based; a couple of spoons can outweigh the rest of a salad.",
        dict(energy_kcal=680, protein_g=1, carb_g=0.6, fat_g=74.8, fiber_g=0, sodium_mg=635, potassium_mg=20, calcium_mg=8, iron_mg=0.2, magnesium_mg=1, zinc_mg=0.1, vitamin_a_ug=40, vitamin_c_mg=0, folate_ug=2, vitamin_b12_ug=0.2, vitamin_d_ug=0.3),
    ),
    (
        "turmeric",
        "Turmeric powder",
        ["haldi", "turmeric"],
        "raw",
        2,
        None,
        "Used by the pinch; nutritionally negligible at that dose.",
        dict(energy_kcal=312, protein_g=9.7, carb_g=67, fat_g=3.3, fiber_g=22.7, sodium_mg=27, potassium_mg=2080, calcium_mg=168, iron_mg=55, magnesium_mg=208, zinc_mg=4.5, vitamin_a_ug=0, vitamin_c_mg=0.7, folate_ug=20, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "cumin",
        "Cumin seed / powder",
        ["jeera", "cumin", "cumin powder", "jeera powder"],
        "raw",
        2,
        None,
        "Spice quantities; a notable iron source by weight but rarely by dose.",
        dict(energy_kcal=375, protein_g=17.8, carb_g=44.2, fat_g=22.3, fiber_g=10.5, sodium_mg=168, potassium_mg=1788, calcium_mg=931, iron_mg=66.4, magnesium_mg=366, zinc_mg=4.8, vitamin_a_ug=64, vitamin_c_mg=7.7, folate_ug=10, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "black_pepper",
        "Black pepper",
        ["kali mirch", "pepper", "black pepper powder"],
        "raw",
        2,
        None,
        "Used by the pinch.",
        dict(energy_kcal=251, protein_g=10.4, carb_g=64, fat_g=3.3, fiber_g=25.3, sodium_mg=20, potassium_mg=1329, calcium_mg=443, iron_mg=9.7, magnesium_mg=171, zinc_mg=1.2, vitamin_a_ug=27, vitamin_c_mg=0, folate_ug=10, vitamin_b12_ug=0, vitamin_d_ug=0),
    ),
    (
        "chicken_breast_raw",
        "Chicken breast, raw (skinless)",
        ["chicken breast", "boneless chicken", "boneless chicken breast", "chicken"],
        "raw",
        150,
        None,
        "Lean protein; raw weight loses roughly a quarter on cooking.",
        dict(energy_kcal=120, protein_g=22.5, carb_g=0, fat_g=2.6, fiber_g=0, sodium_mg=45, potassium_mg=334, calcium_mg=5, iron_mg=0.7, magnesium_mg=28, zinc_mg=0.8, vitamin_a_ug=9, vitamin_c_mg=0, folate_ug=4, vitamin_b12_ug=0.2, vitamin_d_ug=0.1),
    ),
]

FOODS: list[FoodItem] = []
for row in _RAW:
    fid, name, names, form, default_g, piece_g, notes, nut = row
    FOODS.append(
        FoodItem(
            id=fid,
            name=name,
            names=names,
            form=form,
            source="starter",
            default_grams=default_g,
            piece_grams=piece_g,
            health_notes=notes,
            nutrients_per_100g=Nutrients(**nut),
        )
    )


def foods_by_id() -> dict[str, FoodItem]:
    return {f.id: f for f in FOODS}
